troubleshooting workflow

diff --git a/.github/workflows/master.yaml b/.github/workflows/master.yaml
--- a/.github/workflows/master.yaml
+++ b/.github/workflows/master.yaml
@@ -36,19 +36,40 @@ jobs:
       - name: Deploy to Cloud Instance
         uses: appleboy/ssh-action@master
         with:
-          # AWS IP
           host: ${{ secrets.PRODUCTION_AWS_SSH_HOST }}
-          # AWS username
           username: ${{ secrets.PRODUCTION_AWS_SSH_USERNAME }}
-          # SSH key (copy it from your local machine)
           key: ${{ secrets.PRODUCTION_AWS_SSH_SECRET}}
-          # SSH
           script: |
+            echo "Checking and installing Docker if necessary"
+            if ! command -v docker &> /dev/null
+            then
+              echo "Docker not found. Installing..."
+              curl -fsSL https://get.docker.com -o get-docker.sh
+              sh get-docker.sh
+              sudo usermod -aG docker $USER
+              newgrp docker
+            else
+              echo "Docker is already installed"
+            fi
+
+            echo "Checking and installing Docker Compose if necessary"
+            if ! command -v docker-compose &> /dev/null
+            then
+              echo "Docker Compose not found. Installing..."
+              sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
+              sudo chmod +x /usr/local/bin/docker-compose
+            else
+              echo "Docker Compose is already installed"
+            fi
+
             echo "Login to Docker Hub"
             docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
+
             echo "Pull new image"
-            docker compose -f /home/${{ secrets.PRODUCTION_AWS_SSH_USERNAME }}/docker-compose.deploy.yml pull
+            docker-compose -f /home/${{ secrets.PRODUCTION_AWS_SSH_USERNAME }}/docker-compose.deploy.yml pull
+
             echo "Restart the container"
-            docker compose -f /home/${{ secrets.PRODUCTION_AWS_SSH_USERNAME }}/docker-compose.deploy.yml --env-file /home/${{ secrets.PRODUCTION_AWS_SSH_USERNAME }}/.env up --force-recreate --build --no-deps -d
+            docker-compose -f /home/${{ secrets.PRODUCTION_AWS_SSH_USERNAME }}/docker-compose.deploy.yml --env-file /home/${{ secrets.PRODUCTION_AWS_SSH_USERNAME }}/.env up --force-recreate --build --no-deps -d
+
             echo "Delete old image"
             docker image prune -f
